# @package _global_

dataset:
  name: Other_heat
  in_dim: ${dataset.cls.input_length}
  edge_dim: 0
  out_dim: 1
  cls:
    _target_: src.data.dataset.single_mesh_pde.SingleMeshPDE
    root: "${work_dir}/data/fineness/heat/reduce_0.998"
    pre_transform_str: ""
    processed_dir_str: "processed_train"
    maxT: 100
    num_samples: 15
    input_length: 5
    output_length: 3

loss:
  _target_: torch.nn.MSELoss

model:
  _target_: src.run.pde.PDERegressor

engine:
  _target_: src.run.pde.PDEEngine
  device: ${device}
  disable_tqdm: false
  grad_accum_steps: 1
