# @package _global_

train:
  epochs: 100
  batch_size: 1
  lr: 5e-3

optimizer:
  _target_: torch.optim.Adam
  lr: ${train.lr}
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.epochs}

# params: 23,122
backbone:
  net:
    message_dims:
      - - ${dataset.in_dim}
        - 12
        - 12
        - 12
        - 12
    message_orders:
      - - 0
        - 2
        - 2
        - 2
        - 2
    update_dims:
      - - 12
        - ${dataset.out_dim}
    update_orders:
      - - 2
        - 0
    edge_dims: ${dataset.edge_dim}
    final_activation: false
    node_batch_size: null
